spring:
  application:
    name: "kito"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
        '[jdbc.time_zone]': UTC
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  jackson:
    serialization:
      indent-output: true